[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"


[tool.poetry]
name = "final-class"
version = "0.2.0"
description = "Final classes for Python 3"
authors = ["sobolevn <mail@sobolevn.me>"]
license = "MIT"

readme = "README.md"

repository = "https://github.com/moscow-python-beer/final-class"
homepage = "https://github.com/moscow-python-beer/final-class"

keywords = [
    "oop",
    "oop-principles",
    "final-classes",
    "wemake.services",
    "final",
    "final classes",
    "typing"
]

[tool.poetry.dependencies]
python = "^3.6"
typing_extensions = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.1"
pytest-randomly = "^3.1"
pytest-cov = "^2.5"

wemake-python-styleguide = "^0.12.5"
flake8-pytest = "^1.3"
flake8-pytest-style = "^0.1.3"
flake8-pyi = "^19.3"
nitpick = "^0.21.0"

mypy = "^0.720"
safety = "^1.8"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
